/**
 * languages.js
 * 211 world languages — Tamil first, then Top 10 most-spoken, then A–Z.
 * The `code` field is the full language name sent to the AI prompt.
 */
export const LANGUAGES = [
  // ── PINNED FIRST ─────────────────────────────────────────────────
  { code: 'Tamil',             name: 'Tamil',              native: 'தமிழ்' },

  // ── TOP 10 MOST-SPOKEN (excluding Tamil, already above) ──────────
  { code: 'Mandarin Chinese',  name: 'Mandarin Chinese',   native: '中文 (普通话)' },
  { code: 'English',           name: 'English',            native: 'English' },
  { code: 'Hindi',             name: 'Hindi',              native: 'हिन्दी' },
  { code: 'Spanish',           name: 'Spanish',            native: 'Español' },
  { code: 'Arabic',            name: 'Arabic',             native: 'العربية' },
  { code: 'Bengali',           name: 'Bengali',            native: 'বাংলা' },
  { code: 'French',            name: 'French',             native: 'Français' },
  { code: 'Russian',           name: 'Russian',            native: 'Русский' },
  { code: 'Portuguese',        name: 'Portuguese',         native: 'Português' },
  { code: 'Urdu',              name: 'Urdu',               native: 'اردو' },

  // ── A–Z REMAINDER ────────────────────────────────────────────────
  { code: 'Abkhazian',         name: 'Abkhazian',          native: 'Аԥсуа' },
  { code: 'Afar',              name: 'Afar',               native: 'Qafár af' },
  { code: 'Afrikaans',         name: 'Afrikaans',          native: 'Afrikaans' },
  { code: 'Akan',              name: 'Akan',               native: 'Akan' },
  { code: 'Albanian',          name: 'Albanian',           native: 'Shqip' },
  { code: 'Amharic',           name: 'Amharic',            native: 'አማርኛ' },
  { code: 'Armenian',          name: 'Armenian',           native: 'Հայերեն' },
  { code: 'Assamese',          name: 'Assamese',           native: 'অসমীয়া' },
  { code: 'Avaric',            name: 'Avaric',             native: 'Авар' },
  { code: 'Aymara',            name: 'Aymara',             native: 'Aymar' },
  { code: 'Azerbaijani',       name: 'Azerbaijani',        native: 'Azərbaycan' },
  { code: 'Bambara',           name: 'Bambara',            native: 'Bamanankan' },
  { code: 'Bashkir',           name: 'Bashkir',            native: 'Башҡорт' },
  { code: 'Basque',            name: 'Basque',             native: 'Euskara' },
  { code: 'Belarusian',        name: 'Belarusian',         native: 'Беларуская' },
  { code: 'Bihari',            name: 'Bihari',             native: 'भोजपुरी' },
  { code: 'Bislama',           name: 'Bislama',            native: 'Bislama' },
  { code: 'Bosnian',           name: 'Bosnian',            native: 'Bosanski' },
  { code: 'Breton',            name: 'Breton',             native: 'Brezhoneg' },
  { code: 'Bulgarian',         name: 'Bulgarian',          native: 'Български' },
  { code: 'Burmese',           name: 'Burmese',            native: 'မြန်မာ' },
  { code: 'Cantonese',         name: 'Cantonese',          native: '粵語' },
  { code: 'Catalan',           name: 'Catalan',            native: 'Català' },
  { code: 'Chamorro',          name: 'Chamorro',           native: 'Chamoru' },
  { code: 'Chechen',           name: 'Chechen',            native: 'Нохчийн' },
  { code: 'Chewa',             name: 'Chewa (Nyanja)',     native: 'Chichewa' },
  { code: 'Chuukese',          name: 'Chuukese',           native: 'Chuuk' },
  { code: 'Cornish',           name: 'Cornish',            native: 'Kernewek' },
  { code: 'Corsican',          name: 'Corsican',           native: 'Corsu' },
  { code: 'Cree',              name: 'Cree',               native: 'ᓀᐦᐃᔭᐍᐏᐣ' },
  { code: 'Croatian',          name: 'Croatian',           native: 'Hrvatski' },
  { code: 'Czech',             name: 'Czech',              native: 'Čeština' },
  { code: 'Danish',            name: 'Danish',             native: 'Dansk' },
  { code: 'Divehi',            name: 'Divehi (Maldivian)', native: 'ދިވެހި' },
  { code: 'Dogri',             name: 'Dogri',              native: 'डोगरी' },
  { code: 'Dutch',             name: 'Dutch',              native: 'Nederlands' },
  { code: 'Dzongkha',          name: 'Dzongkha',           native: 'རྫོང་ཁ' },
  { code: 'Estonian',          name: 'Estonian',           native: 'Eesti' },
  { code: 'Ewe',               name: 'Ewe',                native: 'Eʋegbe' },
  { code: 'Faroese',           name: 'Faroese',            native: 'Føroyskt' },
  { code: 'Fijian',            name: 'Fijian',             native: 'Vosa Vakaviti' },
  { code: 'Filipino',          name: 'Filipino (Tagalog)',  native: 'Filipino' },
  { code: 'Finnish',           name: 'Finnish',            native: 'Suomi' },
  { code: 'Fula',              name: 'Fula (Fulani)',       native: 'Fulfulde' },
  { code: 'Galician',          name: 'Galician',           native: 'Galego' },
  { code: 'Georgian',          name: 'Georgian',           native: 'ქართული' },
  { code: 'German',            name: 'German',             native: 'Deutsch' },
  { code: 'Greek',             name: 'Greek',              native: 'Ελληνικά' },
  { code: 'Guarani',           name: 'Guarani',            native: 'Avañe\'ẽ' },
  { code: 'Gujarati',          name: 'Gujarati',           native: 'ગુજરાતી' },
  { code: 'Haitian Creole',    name: 'Haitian Creole',     native: 'Kreyòl ayisyen' },
  { code: 'Hakka',             name: 'Hakka Chinese',      native: '客家語' },
  { code: 'Hausa',             name: 'Hausa',              native: 'Hausa' },
  { code: 'Hawaiian',          name: 'Hawaiian',           native: 'ʻŌlelo Hawaiʻi' },
  { code: 'Hebrew',            name: 'Hebrew',             native: 'עברית' },
  { code: 'Herero',            name: 'Herero',             native: 'Otjiherero' },
  { code: 'Hungarian',         name: 'Hungarian',          native: 'Magyar' },
  { code: 'Icelandic',         name: 'Icelandic',          native: 'Íslenska' },
  { code: 'Igbo',              name: 'Igbo',               native: 'Igbo' },
  { code: 'Ilocano',           name: 'Ilocano',            native: 'Ilokano' },
  { code: 'Indonesian',        name: 'Indonesian',         native: 'Bahasa Indonesia' },
  { code: 'Interlingua',       name: 'Interlingua',        native: 'Interlingua' },
  { code: 'Irish',             name: 'Irish (Gaelic)',      native: 'Gaeilge' },
  { code: 'Italian',           name: 'Italian',            native: 'Italiano' },
  { code: 'Japanese',          name: 'Japanese',           native: '日本語' },
  { code: 'Javanese',          name: 'Javanese',           native: 'Basa Jawa' },
  { code: 'Kannada',           name: 'Kannada',            native: 'ಕನ್ನಡ' },
  { code: 'Kashmiri',          name: 'Kashmiri',           native: 'کشمیری' },
  { code: 'Kazakh',            name: 'Kazakh',             native: 'Қазақша' },
  { code: 'Khmer',             name: 'Khmer',              native: 'ភាសាខ្មែរ' },
  { code: 'Kinyarwanda',       name: 'Kinyarwanda',        native: 'Ikinyarwanda' },
  { code: 'Kirghiz',           name: 'Kyrgyz',             native: 'Кыргызча' },
  { code: 'Komi',              name: 'Komi',               native: 'Коми' },
  { code: 'Kongo',             name: 'Kongo',              native: 'Kikongo' },
  { code: 'Korean',            name: 'Korean',             native: '한국어' },
  { code: 'Kurdish',           name: 'Kurdish (Kurmanji)', native: 'Kurdî' },
  { code: 'Lao',               name: 'Lao',                native: 'ພາສາລາວ' },
  { code: 'Latin',             name: 'Latin',              native: 'Latina' },
  { code: 'Latvian',           name: 'Latvian',            native: 'Latviešu' },
  { code: 'Lingala',           name: 'Lingala',            native: 'Lingála' },
  { code: 'Lithuanian',        name: 'Lithuanian',         native: 'Lietuvių' },
  { code: 'Luba-Katanga',      name: 'Luba-Katanga',       native: 'Tshiluba' },
  { code: 'Luganda',           name: 'Luganda',            native: 'Luganda' },
  { code: 'Luxembourgish',     name: 'Luxembourgish',      native: 'Lëtzebuergesch' },
  { code: 'Macedonian',        name: 'Macedonian',         native: 'Македонски' },
  { code: 'Malagasy',          name: 'Malagasy',           native: 'Malagasy' },
  { code: 'Malay',             name: 'Malay',              native: 'Bahasa Melayu' },
  { code: 'Malayalam',         name: 'Malayalam',          native: 'മലയാളം' },
  { code: 'Maltese',           name: 'Maltese',            native: 'Malti' },
  { code: 'Manipuri',          name: 'Manipuri (Meitei)',  native: 'মৈতৈলোন্' },
  { code: 'Maori',             name: 'Māori',              native: 'Te Reo Māori' },
  { code: 'Marathi',           name: 'Marathi',            native: 'मराठी' },
  { code: 'Marshallese',       name: 'Marshallese',        native: 'Kajin M̧ajeļ' },
  { code: 'Min Nan',           name: 'Min Nan Chinese',    native: '閩南語' },
  { code: 'Moldovan',          name: 'Moldovan',           native: 'Moldovenească' },
  { code: 'Mongolian',         name: 'Mongolian',          native: 'Монгол' },
  { code: 'Nauru',             name: 'Nauruan',            native: 'Ekakairũ Naoero' },
  { code: 'Nepali',            name: 'Nepali',             native: 'नेपाली' },
  { code: 'Norwegian',         name: 'Norwegian',          native: 'Norsk' },
  { code: 'Odia',              name: 'Odia (Oriya)',        native: 'ଓଡ଼ିଆ' },
  { code: 'Ossetic',           name: 'Ossetic',            native: 'Ирон' },
  { code: 'Pashto',            name: 'Pashto',             native: 'پښتو' },
  { code: 'Persian',           name: 'Persian (Farsi)',     native: 'فارسی' },
  { code: 'Polish',            name: 'Polish',             native: 'Polski' },
  { code: 'Punjabi',           name: 'Punjabi',            native: 'ਪੰਜਾਬੀ' },
  { code: 'Quechua',           name: 'Quechua',            native: 'Runa Simi' },
  { code: 'Romanian',          name: 'Romanian',           native: 'Română' },
  { code: 'Romansh',           name: 'Romansh',            native: 'Rumantsch' },
  { code: 'Rundi',             name: 'Rundi (Kirundi)',     native: 'Ikirundi' },
  { code: 'Samoan',            name: 'Samoan',             native: 'Gagana Samoa' },
  { code: 'Sango',             name: 'Sango',              native: 'Sängö' },
  { code: 'Sanskrit',          name: 'Sanskrit',           native: 'संस्कृतम्' },
  { code: 'Santali',           name: 'Santali',            native: 'ᱥᱟᱱᱛᱟᱲᱤ' },
  { code: 'Sardinian',         name: 'Sardinian',          native: 'Sardu' },
  { code: 'Scottish Gaelic',   name: 'Scottish Gaelic',    native: 'Gàidhlig' },
  { code: 'Serbian',           name: 'Serbian',            native: 'Српски' },
  { code: 'Shona',             name: 'Shona',              native: 'ChiShona' },
  { code: 'Sindhi',            name: 'Sindhi',             native: 'سنڌي' },
  { code: 'Sinhalese',         name: 'Sinhalese',          native: 'සිංහල' },
  { code: 'Slovak',            name: 'Slovak',             native: 'Slovenčina' },
  { code: 'Slovenian',         name: 'Slovenian',          native: 'Slovenščina' },
  { code: 'Somali',            name: 'Somali',             native: 'Soomaali' },
  { code: 'Sotho',             name: 'Sotho (Sesotho)',     native: 'Sesotho' },
  { code: 'Southern Ndebele',  name: 'Southern Ndebele',   native: 'isiNdebele' },
  { code: 'Sundanese',         name: 'Sundanese',          native: 'Basa Sunda' },
  { code: 'Swahili',           name: 'Swahili',            native: 'Kiswahili' },
  { code: 'Swati',             name: 'Swati (Swazi)',       native: 'siSwati' },
  { code: 'Swedish',           name: 'Swedish',            native: 'Svenska' },
  { code: 'Tajik',             name: 'Tajik',              native: 'Тоҷикӣ' },
  { code: 'Telugu',            name: 'Telugu',             native: 'తెలుగు' },
  { code: 'Thai',              name: 'Thai',               native: 'ภาษาไทย' },
  { code: 'Tibetan',           name: 'Tibetan',            native: 'བོད་སྐད' },
  { code: 'Tigrinya',          name: 'Tigrinya',           native: 'ትግርኛ' },
  { code: 'Tok Pisin',         name: 'Tok Pisin',          native: 'Tok Pisin' },
  { code: 'Tonga',             name: 'Tonga',              native: 'Lea Faka-Tonga' },
  { code: 'Tswana',            name: 'Tswana',             native: 'Setswana' },
  { code: 'Tsonga',            name: 'Tsonga',             native: 'Xitsonga' },
  { code: 'Turkish',           name: 'Turkish',            native: 'Türkçe' },
  { code: 'Turkmen',           name: 'Turkmen',            native: 'Türkmen' },
  { code: 'Twi',               name: 'Twi (Asante)',        native: 'Twi' },
  { code: 'Ukrainian',         name: 'Ukrainian',          native: 'Українська' },
  { code: 'Umbundu',           name: 'Umbundu',            native: 'Umbundu' },
  { code: 'Uzbek',             name: 'Uzbek',              native: 'O\'zbek' },
  { code: 'Venda',             name: 'Venda',              native: 'Tshivenḓa' },
  { code: 'Vietnamese',        name: 'Vietnamese',         native: 'Tiếng Việt' },
  { code: 'Volapük',           name: 'Volapük',            native: 'Volapük' },
  { code: 'Walloon',           name: 'Walloon',            native: 'Walon' },
  { code: 'Welsh',             name: 'Welsh',              native: 'Cymraeg' },
  { code: 'Western Frisian',   name: 'Western Frisian',    native: 'Frysk' },
  { code: 'Wolof',             name: 'Wolof',              native: 'Wollof' },
  { code: 'Wu Chinese',        name: 'Wu Chinese',         native: '吴语' },
  { code: 'Xhosa',             name: 'Xhosa',              native: 'isiXhosa' },
  { code: 'Yiddish',           name: 'Yiddish',            native: 'ייִדיש' },
  { code: 'Yoruba',            name: 'Yoruba',             native: 'Yorùbá' },
  { code: 'Zhuang',            name: 'Zhuang',             native: 'Cuengh' },
  { code: 'Zulu',              name: 'Zulu',               native: 'isiZulu' },
  // ── Additional to reach 211 ──────────────────────────────────────
  { code: 'Adyghe',            name: 'Adyghe',             native: 'Адыгабзэ' },
  { code: 'Afar',              name: 'Afar',               native: 'Qafár af' },
  { code: 'Aragonese',         name: 'Aragonese',          native: 'Aragonés' },
  { code: 'Aromanian',         name: 'Aromanian',          native: 'Armãneashce' },
  { code: 'Asturian',          name: 'Asturian',           native: 'Asturianu' },
  { code: 'Balinese',          name: 'Balinese',           native: 'Bali' },
  { code: 'Baluchi',           name: 'Baluchi',            native: 'بلوچی' },
  { code: 'Banjar',            name: 'Banjar',             native: 'Bahasa Banjar' },
  { code: 'Bats',              name: 'Bats',               native: 'ბაცბი' },
  { code: 'Betawi',            name: 'Betawi',             native: 'Betawi' },
  { code: 'Bikol',             name: 'Bikol',              native: 'Bikol' },
  { code: 'Cebuano',           name: 'Cebuano',            native: 'Sinugbuanong Bisayâ' },
  { code: 'Chichewa',          name: 'Chichewa',           native: 'Chichewa' },
  { code: 'Chuvash',           name: 'Chuvash',            native: 'Чӑвашла' },
  { code: 'Dinka',             name: 'Dinka',              native: 'Thuɔŋjäŋ' },
  { code: 'Dzo',               name: 'Dzongkha',           native: 'རྫོང་ཁ' },
  { code: 'Erzya',             name: 'Erzya',              native: 'Эрзянь' },
  { code: 'Evenki',            name: 'Evenki',             native: 'Эвэнки' },
  { code: 'Extremaduran',      name: 'Extremaduran',       native: 'Estremeñu' },
  { code: 'Friulian',          name: 'Friulian',           native: 'Furlan' },
  { code: 'Gagauz',            name: 'Gagauz',             native: 'Gagauzça' },
  { code: 'Gan Chinese',       name: 'Gan Chinese',        native: '赣语' },
  { code: 'Gilbertese',        name: 'Gilbertese',         native: 'Te Taetae ni Kiribati' },
  { code: 'Hiligaynon',        name: 'Hiligaynon',         native: 'Ilonggo' },
  { code: 'Ido',               name: 'Ido',                native: 'Ido' },
  { code: 'Ingush',            name: 'Ingush',             native: 'ГӀалгӀай мотт' },
  { code: 'Inuktitut',         name: 'Inuktitut',          native: 'ᐃᓄᒃᑎᑐᑦ' },
  { code: 'Karakalpak',        name: 'Karakalpak',         native: 'Qaraqalpaq' },
  { code: 'Kashubian',         name: 'Kashubian',          native: 'Kaszëbsczi' },
  { code: 'Khasi',             name: 'Khasi',              native: 'Ka Bhoi Ki Khasi' },
  { code: 'Kildin Sami',       name: 'Kildin Sami',        native: 'Кӣллт са̄мь кӣлл' },
  { code: 'Kinyarwanda',       name: 'Kinyarwanda',        native: 'Ikinyarwanda' },
  { code: 'Lezgian',           name: 'Lezgian',            native: 'Лезги' },
  { code: 'Limburgish',        name: 'Limburgish',         native: 'Limburgs' },
  { code: 'Low German',        name: 'Low German',         native: 'Plattdüütsch' },
  { code: 'Luo',               name: 'Luo',                native: 'Dholuo' },
  { code: 'Macedonian',        name: 'Macedonian',         native: 'Македонски' },
  { code: 'Mazandarani',       name: 'Mazandarani',        native: 'مازرونی' },
  { code: 'Meadow Mari',       name: 'Meadow Mari',        native: 'Олык марий' },
  { code: 'Minangkabau',       name: 'Minangkabau',        native: 'Baso Minangkabau' },
  { code: 'Mirandese',         name: 'Mirandese',          native: 'Mirandés' },
  { code: 'Moksha',            name: 'Moksha',             native: 'Мокшень' },
  { code: 'Nahuatl',           name: 'Nahuatl',            native: 'Nāhuatl' },
  { code: 'Nauruan',           name: 'Nauruan',            native: 'Dorerin Naoero' },
  { code: 'Neapolitan',        name: 'Neapolitan',         native: 'Napulitano' },
  { code: 'Niuean',            name: 'Niuean',             native: 'ko e Vagahau Niuē' },
  { code: 'Northern Sami',     name: 'Northern Sami',      native: 'Davvisámegiella' },
  { code: 'Occitan',           name: 'Occitan',            native: 'Occitan' },
  { code: 'Oromo',             name: 'Oromo',              native: 'Afaan Oromoo' },
  { code: 'Pangasinan',        name: 'Pangasinan',         native: 'Pangasinán' },
  { code: 'Papiamento',        name: 'Papiamento',         native: 'Papiamentu' },
  { code: 'Pedi',              name: 'Pedi (Sepedi)',       native: 'Sesotho sa Leboa' },
  { code: 'Picard',            name: 'Picard',             native: 'Picard' },
  { code: 'Rohingya',          name: 'Rohingya',           native: 'Ruáingga' },
  { code: 'Romani',            name: 'Romani',             native: 'Romani' },
  { code: 'Rusyn',             name: 'Rusyn',              native: 'Русиньскый' },
  { code: 'Sakha',             name: 'Sakha (Yakut)',       native: 'Саха тыла' },
  { code: 'Silesian',          name: 'Silesian',           native: 'Ślōnski' },
  { code: 'Sinhala',           name: 'Sinhala',            native: 'සිංහල' },
  { code: 'Sorbian',           name: 'Upper Sorbian',      native: 'Hornjoserbšćina' },
  { code: 'Sranan',            name: 'Sranan Tongo',       native: 'Sranantongo' },
  { code: 'Tagalog',           name: 'Tagalog',            native: 'Tagalog' },
  { code: 'Tahitian',          name: 'Tahitian',           native: 'Reo Mā\'ohi' },
  { code: 'Talysh',            name: 'Talysh',             native: 'Толышский' },
  { code: 'Tat',               name: 'Tat',                native: 'Tati' },
  { code: 'Tamazight',         name: 'Tamazight (Berber)',  native: 'ⵜⴰⵎⴰⵣⵉⵖⵜ' },
  { code: 'Tatar',             name: 'Tatar',              native: 'Татарча' },
  { code: 'Tetum',             name: 'Tetum',              native: 'Tetun' },
  { code: 'Tok Pisin',         name: 'Tok Pisin',          native: 'Tok Pisin' },
  { code: 'Tongan',            name: 'Tongan',             native: 'Lea Faka-Tonga' },
  { code: 'Tumbuka',           name: 'Tumbuka',            native: 'Chitumbuka' },
  { code: 'Tuvaluan',          name: 'Tuvaluan',           native: 'Te Ggana Tuuvalu' },
  { code: 'Udmurt',            name: 'Udmurt',             native: 'Удмурт' },
  { code: 'Uyghur',            name: 'Uyghur',             native: 'ئۇيغۇرچە' },
  { code: 'Võro',              name: 'Võro',               native: 'Võro' },
  { code: 'Waray',             name: 'Waray',              native: 'Winaray' },
  { code: 'Xibe',              name: 'Xibe',               native: 'ᠰᡞᠪᡝ ᡤᡞᠰᡠᠨ' },
  { code: 'Yakut',             name: 'Yakut',              native: 'Саха' },
  { code: 'Zazaki',            name: 'Zazaki',             native: 'Zazaca' },
];
